"""Professional Report Generator — generates structured security reports."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


@dataclass(slots=True)
class ReportSection:
    title: str
    content: str
    severity: str = "INFO"


@dataclass(slots=True)
class SecurityReport:
    target: str
    date: str
    executive_summary: str
    findings: list[ReportSection] = field(default_factory=list)
    mitre_mappings: list[str] = field(default_factory=list)
    ioc_summary: str = ""
    timeline_summary: str = ""
    correlation_summary: str = ""
    posture_score: str = ""
    learning_notes: str = ""
    recommendations: list[str] = field(default_factory=list)
    raw_ai_report: str = ""


class ReportGenerator:
    """Generates professional security reports in multiple formats."""

    def generate(
        self,
        target: str,
        ai_report: str = "",
        rule_findings: list | None = None,
        mitre_mappings: list | None = None,
        ioc_report: object | None = None,
        timeline_events: list | None = None,
        correlation_findings: list | None = None,
        posture_score: object | None = None,
        learning_notes: list | None = None,
        threat_intel_report: object | None = None,
    ) -> SecurityReport:
        """Assemble a structured security report from all analysis outputs."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        report = SecurityReport(
            target=target,
            date=now,
            executive_summary=self._build_executive_summary(
                ai_report, rule_findings, posture_score
            ),
            raw_ai_report=ai_report,
        )

        # Findings from rules
        if rule_findings:
            for finding in rule_findings:
                report.findings.append(ReportSection(
                    title=getattr(finding, "title", str(finding)),
                    content=getattr(finding, "rationale", ""),
                    severity=getattr(finding, "severity", "MEDIUM"),
                ))

        # MITRE ATT&CK
        if mitre_mappings:
            from modules.mitre_mapper import format_mitre_mappings
            report.mitre_mappings = [
                f"{m.technique_id} — {m.technique_name} ({m.tactic})"
                for m in mitre_mappings
            ]

        # IOCs
        if ioc_report and getattr(ioc_report, "has_iocs", False):
            from modules.ioc_extractor import format_ioc_report
            report.ioc_summary = format_ioc_report(ioc_report)

        # Timeline
        if timeline_events:
            from modules.timeline_reconstructor import format_timeline_compact
            report.timeline_summary = format_timeline_compact(timeline_events)

        # Correlations
        if correlation_findings:
            from modules.siem_correlator import format_correlation_findings
            report.correlation_summary = format_correlation_findings(correlation_findings)

        # Posture score
        if posture_score:
            from modules.posture_scorer import format_posture_score
            report.posture_score = format_posture_score(posture_score)

        # Learning notes
        if learning_notes:
            from modules.security_mentor import format_learning_notes
            report.learning_notes = format_learning_notes(learning_notes)

        # Threat intel
        if threat_intel_report and getattr(threat_intel_report, "has_results", False):
            from modules.threat_intel import format_threat_intel_report
            report.ioc_summary += "\n\n" + format_threat_intel_report(threat_intel_report)

        # Recommendations
        report.recommendations = self._extract_recommendations(ai_report)

        return report

    def to_markdown(self, report: SecurityReport) -> str:
        """Render a security report as Markdown."""
        lines: list[str] = []

        lines.append(f"# Freddy Security Report")
        lines.append(f"**Target:** {report.target}")
        lines.append(f"**Date:** {report.date}")
        lines.append(f"**Generated by:** Freddy AI Cybersecurity Copilot")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append(report.executive_summary)
        lines.append("")

        # Posture Score
        if report.posture_score:
            lines.append("## Security Posture Score")
            lines.append(f"```")
            lines.append(report.posture_score)
            lines.append(f"```")
            lines.append("")

        # MITRE ATT&CK
        if report.mitre_mappings:
            lines.append("## MITRE ATT&CK Mapping")
            for mapping in report.mitre_mappings:
                lines.append(f"- {mapping}")
            lines.append("")

        # Findings
        if report.findings:
            lines.append("## Findings")
            for i, finding in enumerate(report.findings, 1):
                lines.append(f"### {i}. [{finding.severity}] {finding.title}")
                lines.append(finding.content)
                lines.append("")

        # Timeline
        if report.timeline_summary:
            lines.append("## Incident Timeline")
            lines.append("```")
            lines.append(report.timeline_summary)
            lines.append("```")
            lines.append("")

        # IOCs
        if report.ioc_summary:
            lines.append("## Indicators of Compromise")
            lines.append(report.ioc_summary)
            lines.append("")

        # Correlations
        if report.correlation_summary:
            lines.append("## SIEM Correlation Findings")
            lines.append(report.correlation_summary)
            lines.append("")

        # Recommendations
        if report.recommendations:
            lines.append("## Recommended Actions")
            for i, rec in enumerate(report.recommendations, 1):
                lines.append(f"{i}. {rec}")
            lines.append("")

        # Learning Notes
        if report.learning_notes:
            lines.append("## Security Learning Notes")
            lines.append(report.learning_notes)
            lines.append("")

        # Full AI Report
        if report.raw_ai_report:
            lines.append("## Full AI Analysis")
            lines.append(report.raw_ai_report)
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by Freddy — AI Cybersecurity Terminal Copilot*")

        return "\n".join(lines)

    def to_json(self, report: SecurityReport) -> str:
        """Render a security report as JSON."""
        data = {
            "target": report.target,
            "date": report.date,
            "executive_summary": report.executive_summary,
            "findings": [
                {"title": f.title, "severity": f.severity, "content": f.content}
                for f in report.findings
            ],
            "mitre_mappings": report.mitre_mappings,
            "posture_score": report.posture_score,
            "ioc_summary": report.ioc_summary,
            "timeline_summary": report.timeline_summary,
            "correlation_summary": report.correlation_summary,
            "recommendations": report.recommendations,
        }
        return json.dumps(data, indent=2)

    def save_report(self, report: SecurityReport, fmt: str = "markdown") -> str:
        """Save report to data/reports/ and return the file path."""
        from config import DATA_REPORTS_DIR

        DATA_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        safe_target = re.sub(r"[^\w.-]", "_", report.target)
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

        if fmt == "json":
            path = DATA_REPORTS_DIR / f"report_{safe_target}_{timestamp}.json"
            path.write_text(self.to_json(report), encoding="utf-8")
        else:
            path = DATA_REPORTS_DIR / f"report_{safe_target}_{timestamp}.md"
            path.write_text(self.to_markdown(report), encoding="utf-8")

        return str(path)

    def _build_executive_summary(
        self, ai_report: str, rule_findings: list | None, posture_score: object | None
    ) -> str:
        """Build the executive summary from available data."""
        parts: list[str] = []

        if posture_score:
            score_val = getattr(posture_score, "score", "?")
            grade = getattr(posture_score, "grade", "?")
            risk = getattr(posture_score, "risk_level", "?")
            parts.append(
                f"The target received a security posture score of {score_val}/100 "
                f"(Grade: {grade}, Risk Level: {risk})."
            )

        if rule_findings:
            severities = {}
            for f in rule_findings:
                sev = getattr(f, "severity", "MEDIUM").upper()
                severities[sev] = severities.get(sev, 0) + 1
            sev_summary = ", ".join(f"{c} {s}" for s, c in sorted(severities.items()))
            parts.append(f"Deterministic rules identified {len(rule_findings)} issues: {sev_summary}.")

        if ai_report:
            # Extract first meaningful sentence from AI report
            for line in ai_report.splitlines():
                stripped = line.strip()
                if stripped and not stripped.startswith("#") and len(stripped) > 20:
                    parts.append(stripped[:300])
                    break

        return " ".join(parts) if parts else "Security assessment completed. Review findings below."

    def _extract_recommendations(self, ai_report: str) -> list[str]:
        """Extract remediation recommendations from the AI report."""
        recs: list[str] = []
        in_remediation = False

        for line in ai_report.splitlines():
            stripped = line.strip()
            upper = stripped.upper()

            if "REMEDIATION" in upper or "RECOMMENDATION" in upper or "HARDENING" in upper:
                in_remediation = True
                continue

            if in_remediation:
                if stripped.startswith(("- ", "• ", "* ", "· ")):
                    rec = re.sub(r"^[-•*·]+\s*", "", stripped).strip()
                    if rec and len(rec) > 5:
                        recs.append(rec)
                elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] in ".)":
                    rec = re.sub(r"^\d+[.)]\s*", "", stripped).strip()
                    if rec and len(rec) > 5:
                        recs.append(rec)
                elif not stripped:
                    continue
                elif stripped.startswith("#") or stripped.isupper():
                    in_remediation = False

            if len(recs) >= 15:
                break

        return recs
